NumPy: intended to bring performance and functionality improvements for numerical computing.


*   From User Perspective: Efficiently broadcast operations across dimensions, provide implementations of many functions across linear algebra, statistics,...
*   From Programming Perspective: enable other package to use numpy arrays as an efficient data interface, efficiently process data without type-checking overhead
*   From Hardware Perspective: enable easy file save and load of n-d arrays, efficiently store n-d arrays in vectorised form to benefit from DRAM locality




NumPy provides


1.   extension package to Python for multi-dimensional arrays
2.   closer to hardware (efficiency)
3.   designed for scientific computation (convenience)
4.   also known as array oriented computing



**Why it is useful:**: memory efficient container that provides fast numerical operations

In [10]:
import numpy as np

# **Performance Comparison**


In [2]:
N = 100000000

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 29.7 s, sys: 4.09 s, total: 33.8 s
Wall time: 34.6 s


In [ ]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 11.2 s, sys: 11.5 s, total: 22.8 s
Wall time: 25.3 s


In [ ]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

CPU times: user 1.5 s, sys: 3.07 s, total: 4.58 s
Wall time: 4.6 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

CPU times: user 16.6 s, sys: 2.9 s, total: 19.5 s
Wall time: 19.9 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 3.74 s, sys: 3.22 s, total: 6.96 s
Wall time: 7.07 s


In [ ]:
# using numpy
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 152 ms, sys: 543 ms, total: 695 ms
Wall time: 690 ms


In [ ]:
# using numpy
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 160 ms, sys: 230 ms, total: 390 ms
Wall time: 388 ms


In [ ]:
# another performance comparison
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# python lists
L = range(1000)
%timeit [i**2 for i in L]

305 µs ± 8.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
a = np.arange(1000)
%timeit a**2

1.55 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# **Creating np Arrays**

In [ ]:
# Using arange() function
# arange() is an array-valued version of the built-in python range function
arr = np.arange(5) # 0, 1, 2, 3...., n-1
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.arange(1, 10, 2) # start, end (exclusive), step-size
arr

array([1, 3, 5, 7, 9])

In [ ]:
# creating a numpy array from a list
arr = np.array([0, 2, 4, 6, 8])
print(arr, type(arr))

[0 2 4 6 8] <class 'numpy.ndarray'>


In [ ]:
# data type of individual items of array
arr.dtype

dtype('int64')

In [ ]:
# ndim: number of dimensions
arr.ndim

1

In [ ]:
# shape: tulpe of array dimensions
arr.shape

(5,)

In [ ]:
# size: total number of elements in the array (in all dimensions)
arr.size

5

In [ ]:
# itemsize: size of each item in Bytes
arr.itemsize

8

In [5]:
a = np.array(["2", 23565010, 10])
print(a)

['2' '23565010' '10']


In [6]:
# Creating 2d array using list of lists
arr2d = np.array(
    [
    [1, 2, 3],
    [4, 5, 6]
    ])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# arr2d[1][0]
# arr2d[1, 0]

23565010

In [ ]:
# number of dimensions
arr2d.ndim

2

In [ ]:
# shape: (tuple of array dimensions)
arr2d.shape

(2, 3)

In [ ]:
# size: total number of elements in the array
arr2d.size

6

In [ ]:
len(arr2d) # returns the size of the first dimension
           # which is 2 rows

2

In [ ]:
# creating 3d array
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.size

12

In [ ]:
# creating 3d arrays of ones
np.ones((2, 3, 4)) # ones() takes shape which is a tuple

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
1729 * np.ones((2, 3, 4), dtype=int)
# Here, the scalar 1729 is broadcasted to each and every point in the 3d array

array([[[1729, 1729, 1729, 1729],
        [1729, 1729, 1729, 1729],
        [1729, 1729, 1729, 1729]],

       [[1729, 1729, 1729, 1729],
        [1729, 1729, 1729, 1729],
        [1729, 1729, 1729, 1729]]])

In [ ]:
# creating 3d array of zeros
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# creating identity matrix

np.eye(3) # returns a 2D array with ones the diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 2) # 3 is number of rows, 2 is number of columns

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# create an array using diag function

a = np.diag([1, 2, 3, 4]) # construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# to extract diagonals from a given array
np.diag(a)

array([1, 2, 3, 4])

In [ ]:
# Normal Distribution

np.random.randn(2, 3) # n in 'randn' denotes normal distribution
# randn(): returns series of numbers which are sampled from a Normal Distribution
# with mean = 0 and variance = 1

array([[-0.75162334,  2.47725844,  1.04317481],
       [-0.0135586 ,  0.24256054,  1.43064833]])

In [ ]:
# Uniform Distribution

np.random.rand(2, 3)
# generates numbers sampled randomly between 0 and 1
# each number is equally likely

array([[0.95975629, 0.99034614, 0.51896738],
       [0.0433452 , 0.43902468, 0.26202174]])

In [ ]:
# create an array using random

# create an array of the given shape and populate it with random samples from uniform distribution
a = np.random.rand(4)
a

array([0.19741331, 0.99388763, 0.20472822, 0.09830817])

In [ ]:
np.random.rand(10, 1)

array([[0.12171747],
       [0.17673083],
       [0.51355435],
       [0.16115666],
       [0.399683  ],
       [0.02539914],
       [0.42608158],
       [0.37326837],
       [0.01945823],
       [0.67983234]])

In [ ]:
# np.random.randint(0, 10, (2, 3))
np.random.randint(0, 100, 10)

array([69, 90, 59, 80, 10, 42, 36, 78, 39, 47])

In [ ]:
np.arange(7, 71, 10)

array([ 7, 17, 27, 37, 47, 57, 67])

In [ ]:
# Using "linspace"

np.linspace(7, 70, 10) # start, end, number of points
# returns a evenly spaced 10 numbers between 7 and 70 (both are inclusive)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
np.array([True, False, True, False, True])

array([ True, False,  True, False,  True])

In [ ]:
str_arr = np.array(["1.4", "2.1", "1.1"])
str_arr

array(['1.4', '2.1', '1.1'], dtype='<U3')

In [ ]:
arr = np.array(str_arr, dtype='float')
arr

array([1.4, 2.1, 1.1])

# **Data Types**


In [ ]:
# Each built-in data type has a character code that uniquely identifies it

a = np.arange(10)
a.dtype

dtype('int64')

In [ ]:
# explicitly, some other data type can be specified
a = np.arange(10, dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# The default data type is float for zeros and ones function

a = np.zeros((3, 3))
print(a); a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [ ]:
d = np.array([1 + 2j, 2 + 4j]) # complex data type
print(d.dtype)

complex128


In [ ]:
b = np.array([True, False, True, False]) # Boolean Data Type
b.dtype

dtype('bool')

In [ ]:
s = np.array(["Ram", "Robert", "Rahim"])
s.dtype

dtype('<U6')

# **Indexing and Slicing**

In [ ]:
a = np.arange(10)

print(a[5]) # indices begin at 0, like other python sequences

In [ ]:
# For multi dimensional arrays, indices are tuples of integers
a = np.diag([1, 2, 3])
print(a[2, 2]) # same as a[2][2]

In [ ]:
a[2, 1] = 5 # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [ ]:
# Slicing
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2] # [startIndex: endIndex(exclusive): step]

array([1, 3, 5, 7])

In [ ]:
# we can also combine assignment and slicing
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

**Copies and Views**


A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block.


**When modifying the view, the original array is modified as well:**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [ ]:
a  #even though we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, c)

False

In [ ]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Fancy Indexing**

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [ ]:
a = np.random.randint(0, 20, 15)
a

array([16, 13,  3,  8, 13,  7,  1,  9, 11, 12,  9,  6, 13,  1, 18])

In [ ]:
mask = (a % 2 == 0)
mask

array([ True, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False,  True])

In [ ]:
extract_from_a = a[mask]

extract_from_a

array([16,  8, 12,  6, 18])

In [ ]:
extract_from_a[0] += 1 # original array is not modifies
print(extract_from_a)
print(a)

[18  8 12  6 18]
[16 13  3  8 13  7  1  9 11 12  9  6 13  1 18]


**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [ ]:
a[mask] = -1
a

array([-1, 13,  3, -1, 13,  7,  1,  9, 11, -1,  9, -1, 13,  1, -1])

**Indexing with an array of integers**

In [ ]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

**Some more examples**

In [ ]:
# creating 3d array
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
# Accessing single element
i = 1; j = 0; k = 2
arr3d[i, j, k]
# arr3d[i][j][k]

9

In [ ]:
# Accessing multiple elements
arr3d[0, :, :]
# arr3d[0]
# show 0th value in 1st dimension

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d[:, 1, :]
# arr3d[:][1][:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr3d % 2 == 0
# returns a boolean matrix of True and False
# True indicates the even number at that place

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
arr3d[arr3d % 2 == 0]
# returns all the even number

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]
# returns odd numbers greater than 3

array([ 5,  7,  9, 11])

In [ ]:
arr3d > 3

array([[[False, False, False],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [ ]:
arr_slice = arr3d[:, :, 0:2]
print(type(arr_slice))
print(arr_slice)

<class 'numpy.ndarray'>
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [ ]:
arr_slice.ndim

3

In [ ]:
arr_slice.shape

(2, 2, 2)

In [ ]:
arr_slice[0, 0, 1]

2

In [ ]:
arr_slice[0, 0, 0] = 1729
print(arr_slice)
arr3d # original array is also changed
      # slicing creates views, not copies

[[[1729    2]
  [   4    5]]

 [[   7    8]
  [  10   11]]]


array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
# To create a copy of an array
arr_slice = np.copy(arr3d[:, :, 0:2])
arr_slice[0, 0, 0] = 1
print(arr_slice)
arr3d

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr = np.random.randint(0, 10, (5))
arr

array([3, 8, 9, 4, 9])

In [ ]:
my_indices = [1, 3, 3]
arr[my_indices]

array([0, 1, 1])

In [ ]:
a = np.array([[1, 2], [3, 4]])
a[0, 0] # is different from
a[[0, 0]]

array([[1, 2],
       [1, 2]])

# **NumPy Operations**




## Elementwise Operations

**1. Basic Operations**

**with scalars**

In [ ]:
a = np.array([1, 2, 3, 4])
a + 1 # Elementwise addition

array([2, 3, 4, 5])

In [ ]:
a ** 2 # Operates on each element

array([ 1,  4,  9, 16])

**All arithmetic operates elementwise**

In [ ]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [ ]:
a * b

array([2., 4., 6., 8.])

In [ ]:
# Matrix Multiplication
c = np.diag([1, 2, 3, 4])
print(c * c) # Element wise multiplication
print("**********")
print(c.dot(c)) # Matrix multiplication

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
**********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [1, 1],
    [0, 1]
])
print(a * b)
print(a.dot(b))

[[1 2]
 [0 4]]
[[1 3]
 [3 7]]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
print(a > b)
print(a == b)

[False False  True False]
[False  True False  True]


In [ ]:
# Array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

# Similar to array_equal
result = (a == b).all()
print(result)
result = (a == c).all()
print(result)

False
True
False
True


**Logical Operations**

In [ ]:
a = np.array([1, 1, 0, 0], dtype=bool)
a = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True]
[ True False  True False]


**Transcendental Functions**

In [ ]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.log(a)

<ipython-input-33-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [ ]:
a = np.arange(4)

a + np.array([1, 2])

## Basic Reductions

In [ ]:
# Computing sums
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [ ]:
# Sum by rows and columns
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
np.sum(x, axis=0)  # column sum(goes along first dimension)

array([3, 3])

In [ ]:
np.sum(x, axis=1)  # rows sum(goes along second dimension)

array([2, 4])

In [ ]:
a = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
# print(a.sum())
print(np.sum(a, axis=0))
print()
print(np.sum(a, axis=1))
print()
print(np.sum(a, axis=2))

[[ 6  8]
 [10 12]]

[[ 4  6]
 [12 14]]

[[ 3  7]
 [11 15]]


In [ ]:
a = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [1, 2, 3]
    ]
])
print(np.sum(a, axis=0))
print()
print(np.sum(a, axis=1))
print()
print(np.sum(a, axis=2))

[[ 8 10 12]
 [ 5  7  9]]

[[ 5  7  9]
 [ 8 10 12]]

[[ 6 15]
 [24  6]]


In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.sum(axis=0))
print()
print(a.sum(axis=1))

[5 7 9]

[ 6 15]


In [ ]:
x = np.array([1, 3, 2])
print(x.min())
print(x.max())

1
3


In [ ]:
print(x.argmin()) # index of minimum element
print(x.argmax()) # index of maximum element

0
1


## Logical Operations


In [ ]:
np.all([True, True, False]) # if all values are true, returns true else false

False

In [ ]:
np.any([True, False, False]) # if at least one value is true returns true

True

In [ ]:
# Note: can be used for array comparisions
a = np.zeros((50, 50))
print(a != 0)
print(np.any(a != 0))

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
False


In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

## Statistics

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [ ]:
np.median(x)

1.5

In [ ]:
np.median(y, axis=0)

array([3., 4., 2.])

In [ ]:
np.median(y, axis=1) #last axis
# axis=-1 mean last axis

array([2., 5.])

In [ ]:
x.std()

0.82915619758885

## Example

Data in populations.txt describes the populations of hares and lynxes (and carrots) in nothern Canada during 20 years.

In [ ]:
# Load the data into NumPy array objects
data = np.loadtxt("populations.txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [ ]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [ ]:
# The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [ ]:
# np.mean(populations, axis=0)
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [ ]:
# Sample standard Deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [ ]:
# Which species has the highest population each year ?
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

## Some Operations

In [ ]:
arr1 = np.zeros((3, 4))
arr2 = np.ones((3, 4))
arr1 + arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)
print(arr1, "\n")
print(arr2, "\n")
# arr1 + arr2
# arr1 - arr2
# arr1 * arr2
arr1 / arr2

[[0.77325473 0.32612085 0.20392834 0.36972177]
 [0.40743657 0.60475153 0.62729551 0.84485684]
 [0.36217272 0.15425163 0.56077827 0.93369078]] 

[[0.40452187 0.94199688 0.23427289 0.99528879]
 [0.30996604 0.33511715 0.73632156 0.37612262]
 [0.91043237 0.47161755 0.89225962 0.4528814 ]] 



array([[1.9115276 , 0.34620162, 0.87047349, 0.37147186],
       [1.31445552, 1.80459735, 0.85193147, 2.24622714],
       [0.39780299, 0.32706932, 0.62849226, 2.0616673 ]])

In [ ]:
np.exp(arr1)

array([[2.16680716, 1.38558281, 1.22621028, 1.44733187],
       [1.50296011, 1.83079725, 1.87253947, 2.32764456],
       [1.43644702, 1.16678445, 1.75203552, 2.54388077]])

In [ ]:
np.log(np.exp(arr1))

array([[0.77325473, 0.32612085, 0.20392834, 0.36972177],
       [0.40743657, 0.60475153, 0.62729551, 0.84485684],
       [0.36217272, 0.15425163, 0.56077827, 0.93369078]])

In [ ]:
# np.sin(arr1)
# np.cos(arr1)
np.sqrt(arr1)

array([[0.87934904, 0.57106992, 0.45158425, 0.60804751],
       [0.63830758, 0.77765772, 0.79201989, 0.91916094],
       [0.60180787, 0.39274881, 0.7488513 , 0.96627676]])

In [ ]:
arr_inv = 1 / arr1
arr_inv

array([[1.2932349 , 3.06634795, 4.90368338, 2.70473656],
       [2.45436978, 1.65357168, 1.59414499, 1.18363249],
       [2.76111357, 6.48291362, 1.78323601, 1.0710184 ]])

In [ ]:
arr1 = np.zeros((3, 5))
arr_inv = 1 / arr1

<ipython-input-99-8ed891e68f9b>:2: RuntimeWarning: divide by zero encountered in true_divide
  arr_inv = 1 / arr1


In [ ]:
arr_inv

array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [ ]:
np.isinf(arr_inv[0, 0])

True

In [ ]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])


# **Exercise on finding number of points outside n-dimensional sphere**

In [ ]:
ndim = 2
npoints = 100000

In [ ]:
points = np.random.rand(npoints, ndim)

In [ ]:
points[0:2, :]

array([[0.39084389, 0.07858963],
       [0.730324  , 0.01578012]])

In [ ]:
dfo = np.zeros((npoints, 1)) # distance from origin
outside_points = 0

In [ ]:
%%time

for i in range(npoints):
    for j in range(ndim):
        dfo[i] += points[i, j] ** 2
    dfo[i] = np.sqrt(dfo[i])
    if dfo[i] > 1:
        outside_points += 1

CPU times: user 204 ms, sys: 0 ns, total: 204 ms
Wall time: 207 ms


In [ ]:
print("Fraction of points outside is", outside_points/npoints)

Fraction of points outside is 0.21291


In [ ]:
# 1 - (pi / 4)
1 - 3.14/4

0.21499999999999997

In [ ]:
# Another approach
%%time
sq_points = points * points
dfo = np.sqrt(np.sum(sq_points, axis = 1))
outside_points = np.sum(dfo > 1) / npoints

CPU times: user 2.91 ms, sys: 0 ns, total: 2.91 ms
Wall time: 3.06 ms


In [ ]:
print("Fraction of points outside is ", outside_points/npoints)

Fraction of points outside is  0.21291


In [ ]:
%%time
outside_points = np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1) / npoints

CPU times: user 2.59 ms, sys: 0 ns, total: 2.59 ms
Wall time: 2.58 ms


In [ ]:
def area_outside_square(npoints, ndim):
    points = np.random.rand(npoints, ndim)
    return np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1) / npoints

In [ ]:
area_outside_square(100000, 2)

0.21277

In [ ]:
for i in range(2, 11):
    print(i, area_outside_square(1000000, i))

2 0.214889
3 0.476362
4 0.691417
5 0.835657
6 0.919468
7 0.963134
8 0.984082
9 0.993493
10 0.997447


# Broadcasting

In [ ]:
arr1 = np.arange(6)

In [ ]:
arr1.shape

(6,)

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1 = arr1.reshape((3, 2))

In [ ]:
arr1.shape

(3, 2)

In [ ]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2 = np.arange(6).reshape((3, 2))
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr2[0].shape

(2,)

In [ ]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [ ]:
arr1 + arr2[0]

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr1 + arr2[0].reshape((1, 2))  # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr2[:, 0]
arr2[:, 0].shape

(3,)

In [ ]:
arr1 + arr2[:, 0].reshape((3, 1))

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 3d example
arr1 = np.arange(24).reshape(2, 3, 4)
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr2 = np.ones((1, 4))
arr2

array([[1., 1., 1., 1.]])

In [ ]:
arr1 + arr2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [ ]:
arr1 = np.arange(4)
arr2 = np.arange(5)
print(arr1.shape, arr2.shape)

(4,) (5,)


In [ ]:
# incompatible - broadcast can't be done
# arr1 + arr2

In [ ]:
arr1.reshape(4, 1) + arr2

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

## Some more broadcasting

In [ ]:
# a = np.tile(np.arange(0, 40, 10), (3, 2)) # 3 -> replicate the array 3 times in the rows
#                                           # 2 -> replicate the array 2 times in the columns


a = np.tile(np.arange(0, 40, 10), (3, 1)) # 3 -> replicate the array 3 times in the rows
                                          # 1 -> replicate the array 1 time in the columns

print(a)
print("**********")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
**********
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
 b = np.array([0, 1, 2])
 b

array([0, 1, 2])

In [ ]:
# Broadcasting is done
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [ ]:
a

array([ 0, 10, 20, 30])

In [ ]:
a = a[:, np.newaxis] # Adds a new axis -> 2D Array
a.shape

(4, 1)

In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a.shape)
a = a[:, np.newaxis]
print(a.shape)
print(a)

(2, 2)
(2, 1, 2)
[[[1 2]]

 [[3 4]]]


# Array Shape Manipulation

**Flattening**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()   # returns a contiguous falttened array.
            # 1-d array containing all the elements


array([1, 2, 3, 4, 5, 6])

In [ ]:
a.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

**Reshaping**

The inverse operation to flattening

In [ ]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [ ]:
b = b.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [ ]:
b[0][0] = 200
a

array([[200,   2,   3],
       [  4,   5,   6]])

In [ ]:
np.shares_memory(a, b)

True

**Note: reshape may also return a copy**

In [ ]:
a = np.zeros((3, 2))
b = a.T.reshape(3 * 2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
print(np.shares_memory(a, b))

False


In [ ]:
print(b.shape)
print(b)

(6,)
[50.  0.  0.  0.  0.  0.]


In [ ]:
a = np.zeros((3, 2))
print(a)
b = a.ravel()
print(b)
print(b.shape)
print(np.shares_memory(a, b))
b[0] = 12
print(b)
print(np.shares_memory(a, b))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0.]
(6,)
True
[12.  0.  0.  0.  0.  0.]
True


In [ ]:
b = b.reshape((3, 2))
print()
print(np.shares_memory(a, b))



True


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.T.ravel().reshape((3, 2))
print(np.shares_memory(a, b)) # returns false because
                              # the order of the element is changed
                              # when we do transpose

False


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.ravel().reshape((3, 2))
print(np.shares_memory(a, b)) # True, because order of elements is not changed

True


**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus

1D array will become 2D Array

2D array will become 3D Array

3D array will become 4D Array and so on...

In [ ]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [ ]:
z[:, np.newaxis]

array([[1],
       [2]])

In [ ]:
z = np.array([
    [1, 2],
    [3, 4]
])
print(z[:1, np.newaxis])
print("***********")
print(z[:, np.newaxis])

[[[1 2]]]
***********
[[[1 2]]

 [[3 4]]]


**Dimension Shuffling**

In [ ]:
a = np.arange(4*3*2).reshape((4, 3, 2))
a.shape

(4, 3, 2)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a[0, 2, 1]

5

In [ ]:
a[0][2][1]

5

**Resizing**

In [ ]:
a = np.arange(4)
a.resize((8, ))
a # Extra zeros will be appended

array([0, 1, 2, 3, 0, 0, 0, 0])

However, it must not be referred somewhere else.

In [ ]:
b = a
a.resize((4, ))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
c = np.arange(4)
c.resize(2, 5)
print(c)
c.resize((2)) # in same cell, it is working
print(c)

[[0 1 2 3 0]
 [0 0 0 0 0]]
[0 1]


In [ ]:
c.resize((2)) # in different cell, it is not working
print(c)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

**Sorting Data**

In [ ]:
# Sorting along an axis
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
# In-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
# Sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print(a)
j

[4 3 1 2]


array([2, 3, 1, 0])

In [ ]:
a[j]

array([1, 2, 3, 4])

# File Handling

In [ ]:
planets_small = np.loadtxt("planets_small.txt",
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))
planets_small

In [ ]:
planets_small.ndim

2

In [ ]:
planets_small.shape

(3, 9)

In [ ]:
planets = np.genfromtxt("planets.txt",
                        skip_header = 1,
                        usecols = [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
planets

In [ ]:
planets.shape

(20, 9)

In [ ]:
# chech if there is any NaN
np.isnan(planets)

In [ ]:
# to replace NaN with -1 wherever it is present
planets_new = np.nan_to_num(planets, nan = -1)
planets_new

In [ ]:
# saving file for human readable format
np.savetxt("planets_new.txt", planets_new,
           delimiter = ",")

In [ ]:
# saving file for later numpy processing
np.save("planets_new", planets_new) # no need to add extension

In [ ]:
!ls -lh
# .npy file size is much more less than .txt file

In [ ]:
# saving multiple files together
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [ ]:
np.savez("many_arrs", arr1, arr2, arr3)

In [ ]:
!ls -lh

In [ ]:
# loaidng the file
arrs = np.load("many_arrs.npz")

In [ ]:
type(arrs)

numpy.lib.npyio.NpzFile

In [ ]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
arrs["arr_0"]

array([[0.7689854 , 0.31439437, 0.86959034, ..., 0.41341167, 0.96371675,
        0.88439299],
       [0.49852934, 0.56682326, 0.49687202, ..., 0.23822048, 0.07210142,
        0.82601852],
       [0.10613343, 0.59502056, 0.03328345, ..., 0.41786507, 0.65202893,
        0.65463348],
       ...,
       [0.66750707, 0.00852639, 0.61238547, ..., 0.62591831, 0.72902741,
        0.60699045],
       [0.96227016, 0.99215787, 0.19053078, ..., 0.56494918, 0.84936414,
        0.1495557 ],
       [0.47554461, 0.90882971, 0.05043156, ..., 0.92712993, 0.01838948,
        0.43346205]])

In [ ]:
arrs["arr_0"].shape

(1000, 10)

In [ ]:
# saving compressed the data
np.savez_compressed("many_arrs_compressed",
                    arr1, arr2, arr3)

In [ ]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 2.9K Sep 29 05:39 cric_data.tsv
-rw-r--r-- 1 root root 1.6M Sep 29 06:03 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Sep 29 06:03 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Sep 29 05:54 planets_new.npy
-rw-r--r-- 1 root root 4.5K Sep 29 05:52 planets_new.txt
-rw-r--r-- 1 root root  254 Sep 29 05:39 planets_small.txt
-rw-r--r-- 1 root root 1.5K Sep 29 05:39 planets.txt
drwxr-xr-x 1 root root 4.0K Sep 27 15:30 sample_data


In [ ]:
arr4 = np.zeros((10000, 10000))
np.savez("zeros", arr4)
np.savez_compressed("zeros_compressed", arr4)

In [ ]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 2.9K Sep 29 05:39 cric_data.tsv
-rw-r--r-- 1 root root 1.6M Sep 29 06:03 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Sep 29 06:03 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Sep 29 05:54 planets_new.npy
-rw-r--r-- 1 root root 4.5K Sep 29 05:52 planets_new.txt
-rw-r--r-- 1 root root  254 Sep 29 05:39 planets_small.txt
-rw-r--r-- 1 root root 1.5K Sep 29 05:39 planets.txt
drwxr-xr-x 1 root root 4.0K Sep 27 15:30 sample_data
-rw-r--r-- 1 root root 760K Sep 29 06:06 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Sep 29 06:06 zeros.npz


# Stats with NumPy

In [ ]:
arr = np.random.rand(100000, )

In [ ]:
np.amin(arr)

7.34978889049831e-06

In [ ]:
np.amax(arr)

0.9999916594360453

In [ ]:
np.mean(arr)

0.4977999446902095

In [ ]:
np.var(arr)

0.08360249639526567

In [ ]:
np.std(arr)

0.2891409628455741

In [ ]:
np.median(arr)

0.49702766669976406

In [ ]:
np.percentile(arr, 50) # equivalent to median when 2nd argument is 50

0.49702766669976406

In [ ]:
np.percentile(arr, 10)

0.09895378466177533

In [ ]:
np.percentile(arr, 90)

0.8990377566631056

In [ ]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)
iqr

CPU times: user 6.13 ms, sys: 0 ns, total: 6.13 ms
Wall time: 5.79 ms


0.5019029376578472

In [ ]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]
iqr

CPU times: user 3.29 ms, sys: 0 ns, total: 3.29 ms
Wall time: 3.3 ms


0.5019029376578472

In [ ]:
# Calculating z-score
(arr - np.mean(arr)) / np.std(arr)

array([-0.47120173, -1.05838192, -1.67258729, ..., -1.36806608,
        0.74827903,  0.67957287])

In [ ]:
np.histogram(arr)

(array([10114, 10215, 10023,  9905, 10049, 10033,  9921,  9744, 10113,
         9883]),
 array([7.34978889e-06, 1.00005781e-01, 2.00004212e-01, 3.00002643e-01,
        4.00001074e-01, 4.99999505e-01, 5.99997936e-01, 6.99996367e-01,
        7.99994798e-01, 8.99993228e-01, 9.99991659e-01]))

In [ ]:
np.histogram(arr, bins=5)

(array([20329, 19928, 20082, 19665, 19996]),
 array([7.34978889e-06, 2.00004212e-01, 4.00001074e-01, 5.99997936e-01,
        7.99994798e-01, 9.99991659e-01]))

In [ ]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([25333, 24973, 24876, 24818]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [ ]:
# finds to which bin a number belong to
np.digitize(arr, bins)

array([2, 1, 1, ..., 1, 3, 3])

In [ ]:
arr1 = np.random.randint(0, 10, (10))
arr1

array([3, 7, 8, 2, 2, 3, 1, 7, 9, 2])

In [ ]:
bins = [0, 6, 10]

In [ ]:
np.digitize(arr1, bins)

array([1, 2, 2, 1, 1, 1, 1, 2, 2, 1])

In [ ]:
np.digitize(arr1, bins, right=True)

array([1, 2, 2, 1, 1, 1, 1, 2, 2, 1])

In [ ]:
arr1 = np.random.randint(50, 80, 100) # height

In [ ]:
arr2 = np.random.randint(150, 185, 100) # weight

In [ ]:
arr3 = np.random.randint(17, 22, 100) # age

In [ ]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [ ]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [ ]:
arr2d = np.vstack((arr1, arr2, arr3))

In [ ]:
np.amin(arr2d) # finds minimum across all data

In [ ]:
# finding minimum height
np.amin(arr2d, axis = 1) # 1 is index of column dimension

array([ 50, 150,  17])

In [ ]:
np.amax(arr2d, axis = 1)

array([ 79, 184,  21])

In [ ]:
np.mean(arr2d, axis = 1)

array([ 65.05, 165.77,  18.77])

# Rules of Statistics


Mean subtracted array has zero mean

In [ ]:
arr = np.random.rand(1000)
mean = np.mean(arr)

In [ ]:
arr1 = arr - mean
np.mean(arr1) # non zero value is because of truncation of bits while storing

8.43769498715119e-18

Compuitng mean with smaller set of values

In [ ]:
arr = np.random.rand(1000)
np.mean(arr)

0.5136373902568786

In [ ]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

In [ ]:
# np.cumsum?

In [ ]:
means = np.cumsum(arr)/np.arange(1, 1001)

In [ ]:
means[0:15]

array([0.20763136, 0.28773075, 0.49432594, 0.42776603, 0.47069121,
       0.42215237, 0.37992424, 0.45481838, 0.49327844, 0.45656189,
       0.47491257, 0.45555508, 0.44873843, 0.44766642, 0.45282545])

Effects of Outliers in Mean and Median

In [ ]:
arr = np.random.randint(1, 100, 100)

In [ ]:
np.mean(arr)

49.83

In [ ]:
np.median(arr)

51.0

In [ ]:
arr = np.append(arr, [1000, 2000])

In [ ]:
arr.shape

(102,)

In [ ]:
np.mean(arr)

78.26470588235294

In [ ]:
np.median(arr)

52.0

Effect of Scaling Arrays on Mean and Median

In [ ]:
arr = np.random.rand(100)

In [ ]:
np.mean(arr)

0.4820503983684937

In [ ]:
np.median(arr)

0.44225234893131393

In [ ]:
arr1 = 2.5 * arr + 0.65

In [ ]:
print(np.mean(arr1), 2.5 * np.mean(arr) + 0.65)

1.8551259959212343 1.8551259959212345


In [ ]:
print(np.median(arr1), 2.5 * np.median(arr) + 0.65)

1.755630872328285 1.7556308723282847


In [ ]:
print(np.var(arr1), 2.5 * 2.5 * np.var(arr))

0.4546737416737777 0.4546737416737777


In [ ]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [ ]:
print(np.mean(0.21 * arr1 - 0.75 * arr2),
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.3132422612285743 -0.3132422612285744


# Case Study and Problems




1.   Find mean, median and IQR for Sachin, Rahul and India
2.   Find the Histogram of Sachin's Scores with 10 Bins
3.   Find mean of Sachin's Scores grouped by 25 matches
4.   Find mean of Sachin's Scores where he has scored a century
5.   Find mean of Sachin's Scores when Rahul has Scored less than 10
6.   Find mean for Sachin's Scores based on which Quartile India's Score falls in
7.   For every match  find out who has scored more - Sachin or Rahul
8.   How many more runs does Sachin Score on Average after having scored x runs




In [ ]:
from google.colab import drive
drive.mount('/content/drive')